### ISSUE TITLE
Cannot be used as part of a build using Java 1.8

### ISSUE THREAD

**Issue by marksreeves** [ricksbrown/xslmin#5]
The XSLT minifier fails when run with Java 1.8 with java.lang.RuntimeException: XPathFactory#newInstance() failed to create an XPathFactory due to illegal configuration-file syntax.

**Comment by ricksbrown** [comment]
Closed in PR #6

**Comment by ricksbrown** [comment]
Actually this was misdiagnosed and it did work on Java 8 but it prompted me to fix up a whole bunch of other stuff so yay!
